jaffle_shop:
  outputs:
    dev:
      catalog: '2'
      host: adb-6202383808415066.6.azuredatabricks.net
      http_path: sql/protocolv1/o/6202383808415066/1208-164152-plums54
      schema: DBT - Test
      threads: 1
      token: dapid84e70a12af434e2c20bc8254afb2324
      type: databricks
  target: dev