jaffle_shop:
  outputs:
    dev:
      catalog: '2'
      host: adb-6202383808415066.6.azuredatabricks.net
      http_path: sql/1.0/warehouses/f0ef9c51dab7df22
      schema: dbt_test 
      threads: 1
      token: dapid84e70a12af434e2c20bc8254afb2324
      type: databricks
  target: dev